version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: whisper-warp-postres
    restart: unless-stopped
    environment:
      POSTGRES_USER: A
      POSTGRES_PASSWORD: A
      POSTGRES_DB: A
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  golang:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: whisper-warp-golang
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: whisper-warp-react
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  postgres_data: